### ISSUE TITLE
Need to add Dockerfile

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-damselfly#12]

**Comment by hippo-an** [comment]
@yunkon-kim 
cm-damselfly 의 dockerfile 추가 시점이 언제쯤이 될까요?
dockerfile 추가 시점에 image registry 에 배포 여부도 궁금합니다.

**Comment by yunkon-kim** [comment]
@innodreamer (cc. @hippo-an)

관련하여 계획을 공유하여 주시기 바랍니다.

**Comment by MZC-CSC** [comment]
통합 테스트를 위해 Docker 이미지 배포 부탁드리겠습니다.

**Comment by innodreamer** [comment]
@yunkon-kim @hippo-an @MZC-CSC 
Dockerfile/Docker-compose 적용되었습니다.

**Comment by yunkon-kim** [comment]
Resolved by #21 #23
